<a href="https://colab.research.google.com/github/krakowiakpawel9/neural-network-course/blob/master/02_basics/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [0]:
def max_relu(x):
    return max(x, 0.0)

In [0]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [0]:
data = np.random.randn(50)
data = sorted(data)
data

[-2.1322131508839104,
 -1.8409273792826395,
 -1.5574892237955946,
 -1.4937644093567277,
 -1.416498658038547,
 -1.2552792738658423,
 -1.0747898781652936,
 -0.9841344791659985,
 -0.9785409805513003,
 -0.883046796936672,
 -0.8708802548118862,
 -0.762629714544661,
 -0.604736939437858,
 -0.5694557464994765,
 -0.5053398096349772,
 -0.43871371153876626,
 -0.36584740033693436,
 -0.3306003179524632,
 -0.32431115186952697,
 -0.28187337836925713,
 -0.00952326823609465,
 0.01083186858917424,
 0.039199844761009205,
 0.04611735785621358,
 0.11923207707525554,
 0.12828857711178088,
 0.13051856921551044,
 0.2746065999915435,
 0.34685073967338687,
 0.3493138660799176,
 0.3836628806695486,
 0.5153994346631856,
 0.5934172849170293,
 0.6413015953788903,
 0.654448826789721,
 0.7062741669194295,
 0.7139461430585461,
 0.7550549454676604,
 0.7934473243485926,
 0.9159932006564012,
 0.9847201435920908,
 1.067352346036559,
 1.0853716702575285,
 1.21160873095605,
 1.380914165457712,
 1.592827349188734,
 1.8379409

In [0]:
# wygenerowanie danych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.010832, 0.0392  , 0.046117,
       0.119232, 0.128289, 0.130519, 0.274607, 0.346851, 0.349314,
       0.383663, 0.515399, 0.593417, 0.641302, 0.654449, 0.706274,
       0.713946, 0.755055, 0.793447, 0.915993, 0.98472 , 1.067352,
       1.085372, 1.211609, 1.380914, 1.592827, 1.837941, 2.024925,
       2.20338 , 2.892455])

In [0]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -2.132213            0.0
1 -1.840927            0.0
2 -1.557489            0.0
3 -1.493764            0.0
4 -1.416499            0.0

In [0]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLU Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [0]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [0]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
    print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [0]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-6.552022447328177,
 -6.354996108447863,
 -6.189873087209374,
 -4.444768003438433,
 -4.257342493869493,
 -4.0296106356862245,
 -3.4564040374762035,
 -3.425384338074151,
 -3.258824772703307,
 -3.067365218525207,
 -2.7714326328351477,
 -2.6962220741505885,
 -2.3201295111156988,
 -2.272490197577597,
 -1.972404651364854,
 -1.7450527221622063,
 -1.4307989174952929,
 -1.2648368759874002,
 -1.1991444477475692,
 -1.180072373927835,
 -0.9190574532218161,
 -0.5615031735467947,
 -0.4806473620284958,
 -0.47660864012466464,
 -0.4442029262076751,
 -0.425440721959762,
 -0.37946577570536666,
 -0.2359643088877605,
 -0.19671148091906868,
 0.11315004849573373,
 0.33631831007521706,
 0.5578498629103842,
 0.7184553985053204,
 0.7753493766015358,
 1.150196511057524,
 1.159882009863854,
 1.291421914963482,
 1.3999269775427656,
 1.7367014573647075,
 1.8320091554597997,
 2.0905537838621147,
 2.2078303144923845,
 2.4079095336528717,
 2.4584537601690184,
 2.655301399471724,
 2.9444878341442364,
 3.2340352378653

In [0]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[0.001425192116151768,
 0.0017350264135293344,
 0.002045892661236108,
 0.011603604973243094,
 0.013962179606182656,
 0.017470602800131366,
 0.030578450101989455,
 0.03151149121368672,
 0.037011073087116625,
 0.04447366032646403,
 0.05888756701607384,
 0.0631966512261575,
 0.08946950818642257,
 0.09342708268222667,
 0.1221308380259751,
 0.14867228147769776,
 0.19297423415447193,
 0.22014237480391152,
 0.23162744945462632,
 0.23503918346093294,
 0.2851499836216632,
 0.36319972575439785,
 0.3820992717712857,
 0.38305326462776373,
 0.3907399530119298,
 0.3952155689616097,
 0.40625575192876245,
 0.44128112174231693,
 0.45098009834010894,
 0.5282573704522034,
 0.5832959201513486,
 0.6359548942340535,
 0.6722667946493295,
 0.6846769336520633,
 0.7595468086658389,
 0.7613112747591168,
 0.784387765795795,
 0.8021723007417465,
 0.850267604426731,
 0.8620009004888984,
 0.889981660710615,
 0.9009504752385972,
 0.9174284598949561,
 0.9211774641516757,
 0.9343369885618611,
 0.9500023205604279,
 0.96

In [0]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -6.552022      0.001425
1 -6.354996      0.001735
2 -6.189873      0.002046
3 -4.444768      0.011604
4 -4.257342      0.013962

In [0]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [0]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [0]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-5.30687768144625,
 -4.424333273346425,
 -4.05932068222098,
 -3.598116406008894,
 -3.505868035687177,
 -3.206363694684077,
 -2.9674927724154454,
 -2.96046825948187,
 -2.93873813779757,
 -2.9216021458603065,
 -2.4459182435390514,
 -2.309466433951694,
 -2.155814849526684,
 -2.1125754591093466,
 -2.100616577777817,
 -2.068327530444156,
 -2.0264400143099652,
 -1.911163989500313,
 -1.8622760134264424,
 -1.824670755808279,
 -1.7929982889492744,
 -1.721889395918945,
 -1.6521502103615298,
 -1.649366506258244,
 -1.5871376118729312,
 -1.5433465054892597,
 -1.471514063614081,
 -1.4572130051555165,
 -1.3557342245796684,
 -1.343123769966235,
 -1.2853838871091077,
 -1.2384050579364967,
 -1.147501735057078,
 -1.1057722812161241,
 -1.0790460742049468,
 -1.0635927327526766,
 -1.0464751452214394,
 -0.9968413694523837,
 -0.9403523916951254,
 -0.735542516687622,
 -0.5623754122591677,
 -0.5170515207738202,
 -0.5109479208228045,
 -0.5067960230861588,
 -0.37482399118864723,
 -0.3260913320833328,
 -0.2056394

In [0]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.9999508499531251,
 -0.9997128951072136,
 -0.9994043111390971,
 -0.9985023150869613,
 -0.9981991377978088,
 -0.9967242859678614,
 -0.9947234359052511,
 -0.9946489818781817,
 -0.9944119619290511,
 -0.9942176924876409,
 -0.9850966444508327,
 -0.9804660378236028,
 -0.9735316355347627,
 -0.9711752526662858,
 -0.970487814173077,
 -0.9685500474832317,
 -0.965848745041955,
 -0.9571830722985389,
 -0.9528886988117397,
 -0.9493020659633024,
 -0.9460761001796734,
 -0.9380901366873049,
 -0.9291520923046996,
 -0.9287706400437341,
 -0.9197092980726613,
 -0.9126809907073037,
 -0.8998658839400536,
 -0.8971099523874502,
 -0.8753999773951313,
 -0.8724204978199306,
 -0.8579127659150291,
 -0.845000096704937,
 -0.8169247645530212,
 -0.8025628733982324,
 -0.7928450800670869,
 -0.7870350376005706,
 -0.7804321875467981,
 -0.7602644177824434,
 -0.7353841167161889,
 -0.626444499484768,
 -0.5097377638059992,
 -0.47542116481894375,
 -0.47068344378581395,
 -0.467445059593919,
 -0.3582039829204292,
 -0.315004304

In [0]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -5.306878  -0.999951
1 -4.424333  -0.999713
2 -4.059321  -0.999404
3 -3.598116  -0.998502
4 -3.505868  -0.998199

In [0]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [0]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [0]:
data = np.random.randn(4, 5)
data

array([[-1.435648,  0.602575,  0.359666,  1.010477, -0.369008],
       [-0.053237,  1.305064,  1.941274, -0.499689,  1.603589],
       [ 0.459567,  0.0801  ,  1.586531, -0.310048,  0.248209],
       [ 0.40418 , -1.679086, -0.644682,  0.605058, -0.471173]])

In [0]:
np.exp(data)

array([[0.237961, 1.826816, 1.43285 , 2.74691 , 0.69142 ],
       [0.948155, 3.687924, 6.967622, 0.606719, 4.970842],
       [1.583388, 1.083396, 4.886767, 0.733412, 1.281728],
       [1.498073, 0.186544, 0.52483 , 1.831358, 0.62427 ]])

In [0]:
np.sum(np.exp(data), axis=0)

array([ 4.267578,  6.78468 , 13.812069,  5.9184  ,  7.56826 ])

In [0]:
np.exp(data) / np.sum(np.exp(data), axis=0)

array([[0.05576 , 0.269256, 0.103739, 0.46413 , 0.091358],
       [0.222176, 0.543566, 0.504459, 0.102514, 0.656801],
       [0.371027, 0.159683, 0.353804, 0.123921, 0.169356],
       [0.351036, 0.027495, 0.037998, 0.309435, 0.082485]])

In [0]:
results = softmax(data)
results

array([[0.05576 , 0.269256, 0.103739, 0.46413 , 0.091358],
       [0.222176, 0.543566, 0.504459, 0.102514, 0.656801],
       [0.371027, 0.159683, 0.353804, 0.123921, 0.169356],
       [0.351036, 0.027495, 0.037998, 0.309435, 0.082485]])

In [0]:
np.sum(results, axis=0)

array([1., 1., 1., 1., 1.])