<a href="https://colab.research.google.com/github/Marcin19721205/Wprowadzenie-Do-Sieci-Neuronowych/blob/main/09_Keras01_intro01MJ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#NA RANDOMOWYCH DANYCH BUDOWA MODELI
#KLASYFIKACJI BINARNEJ, WIELOKLASOWEJ I REGRESJI
#KOMPENDIUM JAK BUDOWAĆ MODELE
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Model sekwencjny (Sequential Model):
1. [Wprowadzenie - pierwszy model](#a0)
2. [Funkcje aktywacji](#a1)
3. [Kompilacja modelu](#a2)
4. [Trenowanie modelu](#a3)
5. [Przykład - klasyfikacja binarna](#a4)
6. [Przykład - klasyfikacja wieloklasowa](#a5)
7. [Przykład - regresja](#a6)



Załadowanie biblioteki tensorflow


In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.19.0'

### <a name='a0'></a>Wprowadzenie - pierwszy model
Model sekwencyjny to nic innego jak liniowy stos warstw.

In [2]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential #import klasy sekwencji

model = Sequential()
print(model)

<Sequential name=sequential, built=False>


Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody *.add()*

Pierwszą wartswę okręslamy z iloscią danych wejściowych (tu 10)

In [3]:
from tensorflow.keras.layers import Dense #import klasy dense

model.add(Dense(units=4, input_shape=(10,))) #dodanie warstwy do modelu (units - liczba neuronów w warstwie),input_shapre= rozmaiar danych wejsciowych - 10 kolumn - 10 cech charakterystycznych

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Wyświetlenie podsumowania modelu: metoda *.summary()*

input = 10 + 1 input layer = 11 * 4 neurony (units) = 44 parametry

In [4]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            44 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

Dodanie kolejnej warstwy

Do kulejnych wartw nie musimy już dodawać danycg wejściowych - tylko ilość neuronów

In [5]:
model.add(Dense(units=2))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            44 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

### <a name='a1'></a>Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

Import funkcji liniowej - zwraca to samo y=x

In [6]:
from tensorflow.keras.activations import linear

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -2.691765 -2.691765
1 -2.273767 -2.273767
2 -2.098545 -2.098545
3 -2.083074 -2.083074
4 -2.034557 -2.034557

In [7]:
px.line(data, x='data', y='linear', width=800, range_y=[-2, 2])

Import funkcji sigmoid

In [8]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -2.691765  0.063461
1 -2.273767  0.093319
2 -2.098545  0.109238
3 -2.083074  0.110753
4 -2.034557  0.115622

Zwraca wartości 0 => 1

In [9]:
px.line(data, x='data', y='sigmoid', width=800, range_y=[-0.5, 1.5])

Import relu - zeruje wartości ujemne

In [10]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -2.691765   0.0
1 -2.273767   0.0
2 -2.098545   0.0
3 -2.083074   0.0
4 -2.034557   0.0

In [11]:
px.line(data, x='data', y='relu', width=800, range_y=[-0.5, 1.5])

import tanh. zwraca -1 / 1

In [12]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -2.691765 -0.990859
1 -2.273767 -0.979035
2 -2.098545 -0.970367
3 -2.083074 -0.969450
4 -2.034557 -0.966389

In [13]:
px.line(data, x='data', y='tanh', width=800, range_y=[-1.5, 1.5])

#budowa modelu sequential

tworzenie warstw z zdeniowanymi funkcjami aktywacji

In [14]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid')) #output modelu
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

### <a name='a2'></a>Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
* rodzaj optymalizatora ([Keras - Optymalizatory](https://keras.io/optimizers/))
* funkcję straty ([Keras - Funkcje Straty](https://keras.io/losses/))
* metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki](https://keras.io/metrics/))

# Ważne do koplilacji w zależności od klasy wybieramy optymalizator oraz inną funkcję STRATY

In [16]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [17]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

Wygenerowanie losowych danych

In [50]:
data = np.random.randn(1000, 150) #1000 wierszy, 150 kolumn
labels = np.random.randint(2, size=(1000, 1)) #1000 wierszy, jedna kolumna, dane bool - losuje dane 0-1

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [51]:
data[:3]

array([[-1.19831256e+00,  1.91847582e-01,  9.85233688e-01,
         1.88702570e+00, -1.02869381e+00,  4.29328389e-01,
         1.17973524e+00,  1.88555042e+00, -1.31676552e+00,
         1.17346672e+00, -8.65552980e-01, -7.49789480e-01,
        -3.62116588e-01, -3.26214086e-01,  9.49924110e-01,
        -1.17799057e-01, -1.41985324e+00,  6.73361976e-01,
        -1.85787190e-01,  1.20118971e+00,  6.22234258e-01,
        -2.98690837e-01, -1.97778428e-01,  1.21466040e+00,
         4.61088400e-01,  6.30710144e-01, -1.17633452e+00,
         2.30943541e-01,  7.20010437e-01,  1.11544313e+00,
        -2.12493892e-02,  1.88401942e+00,  1.44051529e+00,
         1.89804674e+00,  5.82858157e-01,  1.23078072e+00,
         7.64826174e-02,  3.77568456e-01, -5.28843555e-01,
         8.30214950e-01, -4.61802153e-01, -7.27666192e-02,
        -8.80950865e-01,  3.37709237e-01, -9.40524827e-01,
        -7.87384496e-01,  1.22875060e-01, -1.26141675e-01,
         6.49586630e-01,  6.08674992e-01, -9.05704534e-0

In [52]:
labels[:10]

array([[0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0]])

Budowa modelu

In [53]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,))) #warstwa ukryta, 32 neurony
model.add(Dense(1, activation='sigmoid')) #wyjście signmoid

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20) #uczenie nadzorowane, przekazujemy labele

Epoch 1/20


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4963 - loss: 0.8308
Epoch 2/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5754 - loss: 0.7074
Epoch 3/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6069 - loss: 0.6573
Epoch 4/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6632 - loss: 0.6174
Epoch 5/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6994 - loss: 0.5947
Epoch 6/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7324 - loss: 0.5523
Epoch 7/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7554 - loss: 0.5358
Epoch 8/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7863 - loss: 0.5082
Epoch 9/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7986 - loss: 0.4798
Epoch 10/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8361 - loss: 0.4577
Epoch 11/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8145 - loss: 0.4465
Epoch 12/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8410 - loss: 0.4329


In [54]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30) #tu dodatkow przekazujemy batch_size - Wagi będą aktualizowane co 30 próbek

Epoch 1/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4987 - loss: 0.8718
Epoch 2/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5361 - loss: 0.7576
Epoch 3/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5992 - loss: 0.6615
Epoch 4/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7036 - loss: 0.5892
Epoch 5/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7231 - loss: 0.5620
Epoch 6/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7699 - loss: 0.5365
Epoch 7/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8096 - loss: 0.5032
Epoch 8/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8190 - loss: 0.4845
Epoch 9/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8266 - loss: 0.4718
Epoch 10/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8544 - loss: 0.4324
Epoch 11/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8695 - loss: 0.4155
Epoch 12/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8899 - lo

In [55]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2) #przekazujemy także validation split

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5017 - loss: 0.8001 - val_accuracy: 0.5150 - val_loss: 0.7593
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5424 - loss: 0.7121 - val_accuracy: 0.4950 - val_loss: 0.7526
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6015 - loss: 0.6677 - val_accuracy: 0.4950 - val_loss: 0.7513
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6320 - loss: 0.6327 - val_accuracy: 0.5100 - val_loss: 0.7507
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6653 - loss: 0.5905 - val_accuracy: 0.5050 - val_loss: 0.7541
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6990 - loss: 0.5784 - val_accuracy: 0.5000 - val_loss: 0.7568
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7653 - loss: 0.5375 - val_accuracy: 0.5200 - val_loss: 0.7636
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8050 - loss: 0.5157 - val_accuracy: 0.5050 - val_loss

In [56]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1) # verbose pokazuje progres

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5012 - loss: 0.7960 - val_accuracy: 0.4750 - val_loss: 0.8382
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5719 - loss: 0.7038 - val_accuracy: 0.4750 - val_loss: 0.8213
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6114 - loss: 0.6564 - val_accuracy: 0.5050 - val_loss: 0.8162
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7005 - loss: 0.5954 - val_accuracy: 0.5150 - val_loss: 0.8152
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7241 - loss: 0.5805 - val_accuracy: 0.5150 - val_loss: 0.8189
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7440 - loss: 0.5624 - val_accuracy: 0.5000 - val_loss: 0.8256
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7738 - loss: 0.5130 - val_accuracy: 0.4900 - val_loss: 0.8342
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8165 - loss: 0.4972 - val_accuracy: 0.4800 - val_loss

Można wyniki treningu wpisać do zmiennej - tutaj history

In [57]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [58]:
metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [59]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5145 - loss: 0.7793 - val_accuracy: 0.4600 - val_loss: 0.7989
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5570 - loss: 0.7037 - val_accuracy: 0.4650 - val_loss: 0.7898
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6170 - loss: 0.6652 - val_accuracy: 0.4700 - val_loss: 0.7880
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6245 - loss: 0.6337 - val_accuracy: 0.4800 - val_loss: 0.7893
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6956 - loss: 0.5964 - val_accuracy: 0.4700 - val_loss: 0.7928
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7241 - loss: 0.5689 - val_accuracy: 0.4650 - val_loss: 0.7984
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7592 - loss: 0.5405 - val_accuracy: 0.4550 - val_loss: 0.8062
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7833 - loss: 0.5102 - val_accuracy: 0.4500 - val_loss

Tworzymy dane testowe data i labels - ten sam format

In [60]:
test_data = np.random.randn(50, 150)
test_labels = np.random.randint(2, size=(50, 1))

In [61]:
model.predict(test_data)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[0.5176579 ],
       [0.72738415],
       [0.2416259 ],
       [0.42400897],
       [0.28414565],
       [0.5316012 ],
       [0.07691874],
       [0.37702462],
       [0.35337025],
       [0.41530585],
       [0.8312159 ],
       [0.38344297],
       [0.44895124],
       [0.08576816],
       [0.96122366],
       [0.14982547],
       [0.37017328],
       [0.4015764 ],
       [0.638196  ],
       [0.8559392 ],
       [0.18938239],
       [0.17753978],
       [0.8398963 ],
       [0.6364577 ],
       [0.37056443],
       [0.5177213 ],
       [0.5778607 ],
       [0.6090212 ],
       [0.430974  ],
       [0.21640408],
       [0.37032083],
       [0.22284526],
       [0.524522  ],
       [0.763474  ],
       [0.73906267],
       [0.3342198 ],
       [0.78140414],
       [0.8168702 ],
       [0.11789402],
       [0.562659  ],
       [0.3598535 ],
       [0.90319645],
       [0.73954546],
       [0.20453988],
       [0.3356318 ],
       [0.94940174],
       [0.5868678 ],
       [0.053

In [62]:
# model.predict_proba(test_data) # predict_proba is deprecated
model.predict(test_data) # Use predict for probabilities with sigmoid/softmax output

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[0.5176579 ],
       [0.72738415],
       [0.2416259 ],
       [0.42400897],
       [0.28414565],
       [0.5316012 ],
       [0.07691874],
       [0.37702462],
       [0.35337025],
       [0.41530585],
       [0.8312159 ],
       [0.38344297],
       [0.44895124],
       [0.08576816],
       [0.96122366],
       [0.14982547],
       [0.37017328],
       [0.4015764 ],
       [0.638196  ],
       [0.8559392 ],
       [0.18938239],
       [0.17753978],
       [0.8398963 ],
       [0.6364577 ],
       [0.37056443],
       [0.5177213 ],
       [0.5778607 ],
       [0.6090212 ],
       [0.430974  ],
       [0.21640408],
       [0.37032083],
       [0.22284526],
       [0.524522  ],
       [0.763474  ],
       [0.73906267],
       [0.3342198 ],
       [0.78140414],
       [0.8168702 ],
       [0.11789402],
       [0.562659  ],
       [0.3598535 ],
       [0.90319645],
       [0.73954546],
       [0.20453988],
       [0.3356318 ],
       [0.94940174],
       [0.5868678 ],
       [0.053

In [63]:
# model.predict_classes(test_data) # predict_classes is deprecated

# Get predicted probabilities
predictions = model.predict(test_data)

# Convert probabilities to class labels (0 or 1) using a threshold of 0.5
predicted_classes = (predictions > 0.5).astype(int)

print(predicted_classes)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]]


### <a name='a5'></a> Przykład - klasyfikacja wieloklasowa

In [68]:
data = np.random.random((1000, 150))
labels = np.random.randint(10, size=(1000, 1)) # losuje liczby 0-9

In [69]:
print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [70]:
data[:3]

array([[0.3513965 , 0.61279205, 0.08619084, 0.41001743, 0.82001929,
        0.53417036, 0.79167815, 0.40194803, 0.72466283, 0.81637022,
        0.7547209 , 0.30308792, 0.33352473, 0.81236363, 0.33121041,
        0.83387152, 0.60748599, 0.02253105, 0.371695  , 0.86901103,
        0.76670792, 0.92907069, 0.08190063, 0.69836023, 0.35659522,
        0.72602423, 0.94799554, 0.66251318, 0.86727478, 0.75337873,
        0.63689746, 0.74262569, 0.91926051, 0.14180005, 0.59069894,
        0.17185716, 0.1153576 , 0.63902648, 0.8474414 , 0.96400037,
        0.95172125, 0.00498662, 0.95987424, 0.49199232, 0.18906955,
        0.0977191 , 0.51488863, 0.93311132, 0.65195779, 0.39397156,
        0.29822292, 0.97393299, 0.31407738, 0.05846822, 0.62367805,
        0.0824014 , 0.4131831 , 0.35661925, 0.18134631, 0.68403884,
        0.86220339, 0.58447458, 0.99729047, 0.5782906 , 0.26968674,
        0.87379698, 0.66754586, 0.41013714, 0.19656457, 0.8981708 ,
        0.05453576, 0.23746517, 0.35467217, 0.86

In [71]:
labels[:10]

array([[4],
       [0],
       [8],
       [9],
       [5],
       [6],
       [6],
       [3],
       [5],
       [3]])

konwersja labeli na macierz odpowiadaącą ilością klas



In [72]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

wświetl wiersz

In [74]:
labels[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Tworzenie modelu, na wyjściu podajemy ile klas, tyle neuronów

In [76]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax')) #dla wieloklasowych dajemy softmax

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.0746 - loss: 2.3747 - val_accuracy: 0.0600 - val_loss: 2.3596
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1294 - loss: 2.3070 - val_accuracy: 0.0850 - val_loss: 2.3392
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1132 - loss: 2.3029 - val_accuracy: 0.0800 - val_loss: 2.3523
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1367 - loss: 2.2751 - val_accuracy: 0.0950 - val_loss: 2.3382
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1486 - loss: 2.2730 - val_accuracy: 0.0750 - val_loss: 2.3520
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1494 - loss: 2.2457 - val_accuracy: 0.0750 - val_loss: 2.3495
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1523 - loss: 2.2376 - val_accuracy: 0.0850 - val_loss: 2.3447
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1455 - loss: 2.2503 - val_accuracy: 0.0900 - val_loss

Dane testowe

In [77]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step


array([[0.05815345, 0.08133271, 0.14320417, 0.05464633, 0.1271601 ,
        0.05287743, 0.23097557, 0.09837051, 0.05306684, 0.10021286],
       [0.06219666, 0.09527636, 0.12932554, 0.2121353 , 0.07379572,
        0.07013243, 0.08120924, 0.09726053, 0.11742897, 0.06123921],
       [0.21198219, 0.05657576, 0.15001357, 0.0360732 , 0.04462072,
        0.05966975, 0.27920225, 0.0832799 , 0.05273279, 0.0258498 ],
       [0.12898219, 0.19530766, 0.09642724, 0.08289304, 0.09288799,
        0.06016622, 0.11242878, 0.09163412, 0.10344229, 0.03583036],
       [0.09864382, 0.24783225, 0.12968542, 0.06694315, 0.04425646,
        0.06843084, 0.03590531, 0.17740895, 0.10385583, 0.02703793],
       [0.21898966, 0.1068857 , 0.13915934, 0.08457888, 0.06119731,
        0.16867872, 0.05840245, 0.06767885, 0.07996628, 0.01446269],
       [0.11149926, 0.07958712, 0.08203351, 0.05107136, 0.06620679,
        0.18020435, 0.0794204 , 0.14264613, 0.19856894, 0.00876211],
       [0.15242524, 0.05066007, 0.0975379

In [79]:
# model.predict_classes(test_data) # predict_classes is deprecated

# Get predicted probabilities
predictions = model.predict(test_data)

# Get the predicted class labels by finding the index of the highest probability
predicted_classes = np.argmax(predictions, axis=1)

print(predicted_classes)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[6 3 6 1 1 0 8 4 3 2]


### <a name='a6'></a> Przykład - regresja

In [80]:
data = np.random.random((1000, 150))
labels = 50 * np.random.random(1000)

In [81]:
data[:3]

array([[0.87500375, 0.85362565, 0.10265017, 0.69380837, 0.18081053,
        0.92024772, 0.75987666, 0.19506109, 0.13867715, 0.71873954,
        0.47710422, 0.99414842, 0.9471718 , 0.17957597, 0.70109177,
        0.89574474, 0.16148005, 0.37779441, 0.85623477, 0.99375446,
        0.38452624, 0.62368543, 0.08313077, 0.03037528, 0.66202235,
        0.28685142, 0.09450833, 0.75837698, 0.41909624, 0.82406012,
        0.63762147, 0.03029182, 0.24583735, 0.28299755, 0.18870449,
        0.49060221, 0.16223319, 0.85214927, 0.78270317, 0.45493556,
        0.23494909, 0.72245033, 0.54503788, 0.02832547, 0.87532829,
        0.3370257 , 0.45482307, 0.69696875, 0.41885512, 0.07481555,
        0.19744289, 0.84662045, 0.8973841 , 0.29669808, 0.54400636,
        0.74636257, 0.62784344, 0.1178968 , 0.78306917, 0.40517936,
        0.12540776, 0.63770184, 0.9234519 , 0.8385374 , 0.8899909 ,
        0.9407708 , 0.20256365, 0.23389619, 0.18515551, 0.99786748,
        0.43662018, 0.83740667, 0.12005191, 0.10

In [82]:
labels[:10]

array([ 4.82692359, 45.77577347, 25.69522374, 48.30110541, 27.51297125,
       18.56857368, 22.93770905, 37.61031129,  4.3469478 , 24.62342377])

In [84]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,))) #spodziewamy się funkcji liniowej, bo relu
model.add(Dense(units=1)) #dla regresji w wyjściowej nie podajemy funkcji aktywacji

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 695.5246 - val_loss: 349.2230
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 335.3961 - val_loss: 223.0144
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 230.7482 - val_loss: 210.2866
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 211.0244 - val_loss: 212.0442
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 210.0828 - val_loss: 211.9794
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 216.7056 - val_loss: 210.5796
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 210.9875 - val_loss: 210.7250
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 214.1577 - val_loss: 209.9929
Epoch 9/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 207.1393 - val_loss: 209.6131
Epoch 10/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 214.0628 - val_loss: 209.8303
Epoch 11/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 212.4851 - val_loss: 209.1495
Epoch 12/30
25/25 ━━━━━━━━━━━━

In [85]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 23.1731 - mse: 752.5546 - val_loss: 18.2626 - val_mse: 500.6177
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.2240 - mse: 495.2832 - val_loss: 15.2287 - val_mse: 353.3963
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.9454 - mse: 379.2810 - val_loss: 13.3443 - val_mse: 255.8345
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.4922 - mse: 254.5396 - val_loss: 12.7050 - val_mse: 216.6877
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.7198 - mse: 218.5820 - val_loss: 12.6343 - val_mse: 210.8928
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.6978 - mse: 215.9875 - val_loss: 12.6345 - val_mse: 210.9282
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.4832 - mse: 211.0541 - val_loss: 12.6440 - val_mse: 211.4132
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.4943 - mse: 208.1489 - val_loss: 12.6355 - val_mse: 210.9337
Epoch 9/30
25/25 ━━━━━━

In [86]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[23.928694],
       [24.07701 ],
       [23.646593],
       [25.301184],
       [24.124104],
       [23.346907],
       [27.087122],
       [20.066717],
       [23.671719],
       [23.288097]], dtype=float32)